//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.07 at 02:00:32 AM BRT 
//


package br.com.alpargatas.materiais.cpq.schema.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemsupplier.categories;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.math.BigDecimal;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemsupplier.categories package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mizuno1_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "mizuno1");
    private final static QName _DooShirts_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "dooShirts");
    private final static QName _Sandalias_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "sandalias");
    private final static QName _JItemSupplierRootIccPrivate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "j_ItemSupplierRootIccPrivate");
    private final static QName _JRevisedItemSupplierAssociation_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "j_RevisedItemSupplierAssociation");
    private final static QName _JRevisedItemSupplierAssociationChangeBitMap_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ChangeBitMap");
    private final static QName _JRevisedItemSupplierAssociationImplementationDate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ImplementationDate");
    private final static QName _JRevisedItemSupplierAssociationJobDefinitionName_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "JobDefinitionName");
    private final static QName _JRevisedItemSupplierAssociationJobDefinitionPackage_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "JobDefinitionPackage");
    private final static QName _JRevisedItemSupplierAssociationLastUpdateLogin_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "LastUpdateLogin");
    private final static QName _JRevisedItemSupplierAssociationPrimaryFlag_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "PrimaryFlag");
    private final static QName _JRevisedItemSupplierAssociationProgramAppName_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ProgramAppName");
    private final static QName _JRevisedItemSupplierAssociationProgramName_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ProgramName");
    private final static QName _JRevisedItemSupplierAssociationRequestId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "RequestId");
    private final static QName _JRevisedItemSupplierAssociationStatusCode_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "StatusCode");
    private final static QName _JRevisedItemSupplierAssociationVersionEndDate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "VersionEndDate");
    private final static QName _JRevisedItemSupplierAssociationVersionStartDate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "VersionStartDate");
    private final static QName _JRevisedItemSupplierAssociationMasterOrganizationId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "MasterOrganizationId");
    private final static QName _JRevisedItemSupplierAssociationContextChangeLineId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ContextChangeLineId");
    private final static QName _JRevisedItemSupplierAssociationContextVersionId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ContextVersionId");
    private final static QName _JRevisedItemSupplierAssociationContextDate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ContextDate");
    private final static QName _JRevisedItemSupplierAssociationItemCatalogGroupId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "ItemCatalogGroupId");
    private final static QName _JRevisedItemSupplierAssociationDuns_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "Duns");
    private final static QName _JRevisedItemSupplierAssociationSupplierName_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "SupplierName");
    private final static QName _JRevisedItemSupplierAssociationSupplierSiteName_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "SupplierSiteName");
    private final static QName _JRevisedItemSupplierAssociationSupplierNumber_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "SupplierNumber");
    private final static QName _JRevisedItemSupplierAssociationRegistryId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "RegistryId");
    private final static QName _JRevisedItemSupplierAssociationCategoryCode_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", "CategoryCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemsupplier.categories
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mizuno1 }
     * 
     */
    public Mizuno1 createMizuno1() {
        return new Mizuno1();
    }

    /**
     * Create an instance of {@link DooShirts }
     * 
     */
    public DooShirts createDooShirts() {
        return new DooShirts();
    }

    /**
     * Create an instance of {@link Sandalias }
     * 
     */
    public Sandalias createSandalias() {
        return new Sandalias();
    }

    /**
     * Create an instance of {@link JItemSupplierRootIccPrivate }
     * 
     */
    public JItemSupplierRootIccPrivate createJItemSupplierRootIccPrivate() {
        return new JItemSupplierRootIccPrivate();
    }

    /**
     * Create an instance of {@link JRevisedItemSupplierAssociation }
     * 
     */
    public JRevisedItemSupplierAssociation createJRevisedItemSupplierAssociation() {
        return new JRevisedItemSupplierAssociation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mizuno1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "mizuno1")
    public JAXBElement<Mizuno1> createMizuno1(Mizuno1 value) {
        return new JAXBElement<Mizuno1>(_Mizuno1_QNAME, Mizuno1 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DooShirts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "dooShirts")
    public JAXBElement<DooShirts> createDooShirts(DooShirts value) {
        return new JAXBElement<DooShirts>(_DooShirts_QNAME, DooShirts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sandalias }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "sandalias")
    public JAXBElement<Sandalias> createSandalias(Sandalias value) {
        return new JAXBElement<Sandalias>(_Sandalias_QNAME, Sandalias.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JItemSupplierRootIccPrivate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "j_ItemSupplierRootIccPrivate")
    public JAXBElement<JItemSupplierRootIccPrivate> createJItemSupplierRootIccPrivate(JItemSupplierRootIccPrivate value) {
        return new JAXBElement<JItemSupplierRootIccPrivate>(_JItemSupplierRootIccPrivate_QNAME, JItemSupplierRootIccPrivate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JRevisedItemSupplierAssociation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "j_RevisedItemSupplierAssociation")
    public JAXBElement<JRevisedItemSupplierAssociation> createJRevisedItemSupplierAssociation(JRevisedItemSupplierAssociation value) {
        return new JAXBElement<JRevisedItemSupplierAssociation>(_JRevisedItemSupplierAssociation_QNAME, JRevisedItemSupplierAssociation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ChangeBitMap", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationChangeBitMap(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationChangeBitMap_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ImplementationDate", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<XMLGregorianCalendar> createJRevisedItemSupplierAssociationImplementationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_JRevisedItemSupplierAssociationImplementationDate_QNAME, XMLGregorianCalendar.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "JobDefinitionName", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationJobDefinitionName(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationJobDefinitionName_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "JobDefinitionPackage", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationJobDefinitionPackage(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationJobDefinitionPackage_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "LastUpdateLogin", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationLastUpdateLogin(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationLastUpdateLogin_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "PrimaryFlag", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Boolean> createJRevisedItemSupplierAssociationPrimaryFlag(Boolean value) {
        return new JAXBElement<Boolean>(_JRevisedItemSupplierAssociationPrimaryFlag_QNAME, Boolean.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ProgramAppName", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationProgramAppName(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationProgramAppName_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ProgramName", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationProgramName(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationProgramName_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "RequestId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<BigDecimal> createJRevisedItemSupplierAssociationRequestId(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_JRevisedItemSupplierAssociationRequestId_QNAME, BigDecimal.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "StatusCode", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Long> createJRevisedItemSupplierAssociationStatusCode(Long value) {
        return new JAXBElement<Long>(_JRevisedItemSupplierAssociationStatusCode_QNAME, Long.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "VersionEndDate", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<XMLGregorianCalendar> createJRevisedItemSupplierAssociationVersionEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_JRevisedItemSupplierAssociationVersionEndDate_QNAME, XMLGregorianCalendar.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "VersionStartDate", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<XMLGregorianCalendar> createJRevisedItemSupplierAssociationVersionStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_JRevisedItemSupplierAssociationVersionStartDate_QNAME, XMLGregorianCalendar.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "MasterOrganizationId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Long> createJRevisedItemSupplierAssociationMasterOrganizationId(Long value) {
        return new JAXBElement<Long>(_JRevisedItemSupplierAssociationMasterOrganizationId_QNAME, Long.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ContextChangeLineId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Long> createJRevisedItemSupplierAssociationContextChangeLineId(Long value) {
        return new JAXBElement<Long>(_JRevisedItemSupplierAssociationContextChangeLineId_QNAME, Long.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ContextVersionId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Long> createJRevisedItemSupplierAssociationContextVersionId(Long value) {
        return new JAXBElement<Long>(_JRevisedItemSupplierAssociationContextVersionId_QNAME, Long.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ContextDate", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<XMLGregorianCalendar> createJRevisedItemSupplierAssociationContextDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_JRevisedItemSupplierAssociationContextDate_QNAME, XMLGregorianCalendar.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "ItemCatalogGroupId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<Long> createJRevisedItemSupplierAssociationItemCatalogGroupId(Long value) {
        return new JAXBElement<Long>(_JRevisedItemSupplierAssociationItemCatalogGroupId_QNAME, Long.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "Duns", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationDuns(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationDuns_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "SupplierName", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationSupplierName(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationSupplierName_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "SupplierSiteName", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationSupplierSiteName(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationSupplierSiteName_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "SupplierNumber", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationSupplierNumber(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationSupplierNumber_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "RegistryId", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationRegistryId(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationRegistryId_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemSupplier/categories/", name = "CategoryCode", scope = JRevisedItemSupplierAssociation.class)
    public JAXBElement<String> createJRevisedItemSupplierAssociationCategoryCode(String value) {
        return new JAXBElement<String>(_JRevisedItemSupplierAssociationCategoryCode_QNAME, String.class, JRevisedItemSupplierAssociation.class, value);
    }

}
