//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.07 at 02:00:32 AM BRT 
//


package br.com.alpargatas.materiais.cpq.schema.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemrevision.categories;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemrevision.categories package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mizuno1_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "mizuno1");
    private final static QName _DooShirts_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "dooShirts");
    private final static QName _Sandalias_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "sandalias");
    private final static QName _JItemRevisionRootIccPrivate_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "j_ItemRevisionRootIccPrivate");
    private final static QName _JItemRevisionVersion_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "j_ItemRevisionVersion");
    private final static QName _JItemRevisionVersionCategoryCode_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "CategoryCode");
    private final static QName _JItemRevisionVersionVersionId_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", "VersionId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemrevision.categories
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mizuno1 }
     * 
     */
    public Mizuno1 createMizuno1() {
        return new Mizuno1();
    }

    /**
     * Create an instance of {@link DooShirts }
     * 
     */
    public DooShirts createDooShirts() {
        return new DooShirts();
    }

    /**
     * Create an instance of {@link Sandalias }
     * 
     */
    public Sandalias createSandalias() {
        return new Sandalias();
    }

    /**
     * Create an instance of {@link JItemRevisionRootIccPrivate }
     * 
     */
    public JItemRevisionRootIccPrivate createJItemRevisionRootIccPrivate() {
        return new JItemRevisionRootIccPrivate();
    }

    /**
     * Create an instance of {@link JItemRevisionVersion }
     * 
     */
    public JItemRevisionVersion createJItemRevisionVersion() {
        return new JItemRevisionVersion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mizuno1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "mizuno1")
    public JAXBElement<Mizuno1> createMizuno1(Mizuno1 value) {
        return new JAXBElement<Mizuno1>(_Mizuno1_QNAME, Mizuno1 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DooShirts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "dooShirts")
    public JAXBElement<DooShirts> createDooShirts(DooShirts value) {
        return new JAXBElement<DooShirts>(_DooShirts_QNAME, DooShirts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sandalias }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "sandalias")
    public JAXBElement<Sandalias> createSandalias(Sandalias value) {
        return new JAXBElement<Sandalias>(_Sandalias_QNAME, Sandalias.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JItemRevisionRootIccPrivate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "j_ItemRevisionRootIccPrivate")
    public JAXBElement<JItemRevisionRootIccPrivate> createJItemRevisionRootIccPrivate(JItemRevisionRootIccPrivate value) {
        return new JAXBElement<JItemRevisionRootIccPrivate>(_JItemRevisionRootIccPrivate_QNAME, JItemRevisionRootIccPrivate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JItemRevisionVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "j_ItemRevisionVersion")
    public JAXBElement<JItemRevisionVersion> createJItemRevisionVersion(JItemRevisionVersion value) {
        return new JAXBElement<JItemRevisionVersion>(_JItemRevisionVersion_QNAME, JItemRevisionVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "CategoryCode", scope = JItemRevisionVersion.class)
    public JAXBElement<String> createJItemRevisionVersionCategoryCode(String value) {
        return new JAXBElement<String>(_JItemRevisionVersionCategoryCode_QNAME, String.class, JItemRevisionVersion.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/apps/scm/productCatalogManagement/advancedItems/flex/egoItemEff/itemRevision/categories/", name = "VersionId", scope = JItemRevisionVersion.class, defaultValue = "-1")
    public JAXBElement<Long> createJItemRevisionVersionVersionId(Long value) {
        return new JAXBElement<Long>(_JItemRevisionVersionVersionId_QNAME, Long.class, JItemRevisionVersion.class, value);
    }

}
